### ISSUE TITLE
pixi-pycharm doesn't work with `pyproject.toml` configuration

### ISSUE THREAD

**Issue by maawoo** [pavelzw/pixi-pycharm#11]
## Description

I guess this is related to #10 as my PyCharm doesn't seem to want to add an environment called `default`. The `Use existing environment`-dropdown is just empty and I can't proceed:

<img width="957" alt="image" src="https://github.com/pavelzw/pixi-pycharm/assets/56583917/a2b1b334-fefb-455d-b907-4f07b2934b5b">

Yes, the `Load Environments`-button has been clicked 😉 

## Versions

```bash
❯ pixi --version
pixi 0.19.1
❯ pixi list | grep pixi-pycharm
pixi-pycharm                   0.0.3           h707e725_0               7.8 KiB    conda  pixi-pycharm-0.0.3-h707e725_0.conda
```

PyCharm version: PyCharm 2024.1 (Professional Edition)
Platform: macOS Sonoma

**Comment by pavelzw** [comment]
Pixi-pycharm writes logs to `pixi-pycharm.log`. Do you see anything of interest there?

**Comment by maawoo** [comment]
Here is the entire output of the logs:
```
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
Attempting to run: ['info', '--envs', '--json']
```

**Comment by maawoo** [comment]
```
./.pixi/envs/default/libexec/conda info --envs --json
{
    "envs_dirs": [
        "/Users/marcowo/Documents/pypypy/woody/.pixi/envs"
    ],
    "conda_prefix": "/Users/marcowo/Documents/pypypy/woody/.pixi/envs",
    "envs": []
}
```

**Comment by pavelzw** [comment]
Hmm interesting, could you share your `pixi.toml`?

**Comment by pavelzw** [comment]
Do you by any chance use `pyproject.toml` instead of `pixi.toml`? This is currently not supported as `pixi.toml` is implicitly assumed: https://github.com/pavelzw/pixi-pycharm/blob/75c3a9731d7a2e96315c9a19f6a396263a1cbab6/conda#L18

**Comment by maawoo** [comment]
I guess that will be it. I have used a `pyproject.toml`. Any chance this will be supported in the near future given that pixi supports both formats now?

**Comment by pavelzw** [comment]
Yes, it's now on my radar 😄 

I'll try to implement it soon, should be a fairly simple fix :)
