### ISSUE TITLE
PyCharm automatic import suggestions

### ISSUE THREAD

**Issue by tibuch** [pavelzw/pixi-pycharm#17]
Hi,

I have this code snippet in PyCharm:
```
def main(
    acquisition_dir: str,
    trace_log_files: list[str],
    order_name: str,
    barcode: str,
):
    img = imread('test.tif')
```
When I configure the interpreter via conda, PyCharm suggests the correct import (`from tifffile import imread`). Now I have configured the interpreter via `pixi-pycharm`, but it will not suggest any imports. 

I can still write and execute the code, but I need to write the imports myself. So this is more a quality of life feature :slightly_smiling_face: 

If I add the import myself, I can run the code via the configured `pixi-pycharm` interpreter :+1:

**Comment by pavelzw** [comment]
Hmm, i cannot seem to reproduce this example...

<img width="880" alt="image" src="https://github.com/pavelzw/pixi-pycharm/assets/29506042/9186a590-1e89-41bb-ae67-f0e4ae0fe324">


<img width="573" alt="image" src="https://github.com/pavelzw/pixi-pycharm/assets/29506042/24f81023-c565-4dfa-bd14-2d4b44b13aff">

This shouldn't have anything to do with using pixi or conda. I think(?) how pycharm finds these things is by finding the correct python executable and then just scanning the site-packages directory of this environment (that's what's happening when you see `Updating skeletons`). 

Maybe pycharm just didn't refresh the skeletons yet?

**Comment by tibuch** [comment]
This is how it looks for me right now:
![issue](https://github.com/pavelzw/pixi-pycharm/assets/5450869/99abc0d8-a85a-4596-abcd-a3f351ddf199)

And I only get these suggestions:
![image](https://github.com/pavelzw/pixi-pycharm/assets/5450869/8a5ee881-cce7-4640-b166-ecf6c3acbceb)

In the `Interpreter Paths` dialog I can click the refresh button, which triggers `Updating skeletons`. But in the end nothing changes. 

Maybe I will try a fresh install of PyCharm next.

**Comment by pavelzw** [comment]
Hmm weird, that looks exactly like my setup...

**Comment by tibuch** [comment]
Sounds like a reasonable assumption. 

I have no idea where this is going wrong. Also resetted the caches of PyCharm, but so far nothing worked.

**Comment by richardsheridan** [comment]
Hi, found this while troubleshooting a different typing problem. Thanks for the screenshots of the External Libraries widget, it gave me an idea what the problem might be. That highlighting is for "non-project" files, so pycharm thinks that items found in the `.pixi` folder are actually project files. My typing symptoms went away when I excluded the `.pixi` folder (right click ->  Mark Directory as -> Excluded). 

It's not clear to me WHY the project vs non-project distinction confuses pycharm so much. However, I don't think there's anything for this project to fix, except maybe document the need to exclude the pixi folder from the project files if it is in the project folder.

**Comment by pavelzw** [comment]
Thanks, that sounds doable! @tibuch could you try if that fixed the issue?

**Comment by tibuch** [comment]
Yes, this works! Thank you @richardsheridan!

But, I can't rename the environment and they are now all called `default`. But I think this is another issue :slightly_smiling_face:

**Comment by pavelzw** [comment]
> they are now all called default

xref #10

**Comment by pavelzw** [comment]
Added some documentation for this in #28
