### ISSUE TITLE
Adding new Python interpreter using the pixi-pycharm plugin fails

### ISSUE THREAD

**Issue by gitkief** [pavelzw/pixi-pycharm#35]
## Description

While trying to use the Pixi-PyCharm integration as described in the [official instructions](https://pixi.sh/v0.30.0/ide_integration/pycharm/)  I encountered a problem: Adding a new Python interpreter with the conda-shim fails.

More specifically:
 
- In the "Add Python interpreter" dialog select "Conda Environment".
- Set the "Conda Executable" equal to the conda shim executable (i.e. the result of  `pixi run 'echo $CONDA_PREFIX/libexec/conda'`)
- In the next step, I am trying to load the available conda environments by pressing "Load Environments". It fails with 
  'Cannot invoke "com.jetbrains.python.sdk.flavors.conda.CondaInfoJson.getEnvs()" because "info" is null'

## Versions

```bash
❯ pixi --version
pixi 0.30.0
❯ pixi list | grep pixi-pycharm
pixi-pycharm      0.0.6      unix_1234567_0      8.6 KiB    conda  pixi-pycharm-0.0.6-unix_1234567_0.conda 
```

PyCharm version: 

PyCharm 2024.2.2 (Community Edition)
Build #PC-242.22855.92, built on September 19, 2024
Runtime version: 21.0.3+13-b509.15 amd64 (JCEF 122.1.9)
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.X11.XToolkit
Linux 6.8.0-45-generic

Platform: Linux

## Logs

```
Attempting to run: ['info', '--envs', '--json']
Traceback (most recent call last):
  File "/home/mike/coding/sandbox/pixitest/.pixi/envs/default/libexec/conda", line 165, in <module>
    sys.exit(main(args))
             ^^^^^^^^^^
  File "/home/mike/coding/sandbox/pixitest/.pixi/envs/default/libexec/conda", line 139, in main
    conda_info_envs_json()
  File "/home/mike/coding/sandbox/pixitest/.pixi/envs/default/libexec/conda", line 79, in conda_info_envs_json
    "envs": pixi_envs(),
            ^^^^^^^^^^^
  File "/home/mike/coding/sandbox/pixitest/.pixi/envs/default/libexec/conda", line 57, in pixi_envs
    platform = pixi_json(["info", *std_pixi_args()])["platform"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/coding/sandbox/pixitest/.pixi/envs/default/libexec/conda", line 53, in pixi_json
    return json.loads(pixi([*cmd, "--json"]))
                      ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/coding/sandbox/pixitest/.pixi/envs/default/libexec/conda", line 22, in pixi
    out = subprocess.check_output(["pixi", *cmd])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/coding/sandbox/pixitest/.pixi/envs/default/lib/python3.12/subprocess.py", line 466, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/coding/sandbox/pixitest/.pixi/envs/default/lib/python3.12/subprocess.py", line 548, in run
    with Popen(*popenargs, **kwargs) as process:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mike/coding/sandbox/pixitest/.pixi/envs/default/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/home/mike/coding/sandbox/pixitest/.pixi/envs/default/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pixi'
```

**Comment by pavelzw** [comment]
This looks like #16 and #20. where is your pixi installed?

**Comment by gitkief** [comment]
Thank you very much for the quick help! pixi is installed under the home location: `~/.pixi/bin/pixi` and in `PATH`. Adding a symlink to `/usr/local/bin` as proposed by #16 fixed the problem! Two small follow up questions:
1) Should the step of creating the symlink be part of the pixi-pycharm installation instruction or do you believe something went wrong while installing pixi?
2) Is there an equivalent location on Windows? Because in a Windows setup I get the same error.

**Comment by pavelzw** [comment]
On windows this shouldn't be a problem if it's properly in PATH. Did you install pixi with the msi from GitHub or with the installation script? It might be that you need to adjust your user environment variables in the latter case.

I should just fix #20, there is nothing wrong with your installation.

**Comment by gitkief** [comment]
You were right in case of Windows! I reinstalled pixi using `winget install prefix-dev.pixi` as noted by the official docs. It seems that the former/older setup caused the problem. Now winget installed pixi v0.28.1 in the local app data (i.e. `~\AppData\Local\pixi\bin`) and added the folder to `PATH`. With that everything works as expected. Thanks again for your support! Please let me know if I can support you with further testing etc.

**Comment by pavelzw** [comment]
Let's close this issue in favor of #20 then :)
